In [82]:
# import pandas as pd
# import numpy as np
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import confusion_matrix, classification_report
# import joblib
# import tensorflow as tf

# # Load the sleep data into a pandas dataframe
# df = pd.read_csv('/kk (1).csv')
# # Dropping NaN values
# df2 = df.dropna()
# # Define the feature variables (X) and target variable (y)
# X = df2[['light sleep (sec)', 'deep (sec)', 'start time from 8pm','end time from 8pm']]
# y = df2['Snooze']

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Fit the logistic regression model to the training data
# logreg = LogisticRegression()
# logreg.fit(X_train, y_train)

# # Predict the snooze count for the testing data
# y_pred = logreg.predict(X_test)

# # Print the confusion matrix and classification report
# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))

# # 1. Export the scikit-learn model to a format compatible with TFLite
# joblib.dump(logreg, 'logreg_model.pkl')

# # 2. Convert the exported model to TensorFlow Lite format
# logreg_model = joblib.load('logreg_model.pkl')

# # Convert the logistic regression model to TFLite
# converter = tf.lite.TFLiteConverter.from_sklearn(model=logreg_model)
# tflite_model = converter.convert()

# # Save the TFLite model to a file
# with open('logreg_model.tflite', 'wb') as f:
#     f.write(tflite_model)


In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

In [84]:
df = pd.read_csv('kk (1).csv')
df2 = df.dropna()
X = df2[['light sleep (sec)', 'deep (sec)', 'start time from 8pm','end time from 8pm','step count']]
y = df2['Snooze']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=22)

print(df.head())

   light sleep (sec)  deep (sec)  start time from 8pm  end time from 8pm  \
0              10140        3300                25260              38700   
1              11760        7620                18900              38280   
2               9540       12420                23220              18900   
3              11880        6300                24540              42720   
4              16920        1500                21180              40680   

   step count  Snooze  
0        9841       5  
1       10123       4  
2        5412       9  
3       11985       4  
4       12111       4  


In [85]:
df.shape

(46, 6)

In [86]:
model = Sequential(
    [ 
        Dense(100, activation = 'relu'),
        Dense(150, activation = 'relu'),
        Dense(50, activation = 'relu'),
        Dense(10, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)


In [87]:

model.fit(
    X_train,y_train,
    epochs=1000
)

Epoch 1/1000


2/2 [==============================] - 1s 5ms/step - loss: 2651.6670
Epoch 2/1000
2/2 [==============================] - 0s 5ms/step - loss: 1280.2972
Epoch 3/1000
2/2 [==============================] - 0s 3ms/step - loss: 1141.6455
Epoch 4/1000
2/2 [==============================] - 0s 2ms/step - loss: 1009.8768
Epoch 5/1000
2/2 [==============================] - 0s 5ms/step - loss: 624.2144
Epoch 6/1000
2/2 [==============================] - 0s 3ms/step - loss: 441.5612
Epoch 7/1000
2/2 [==============================] - 0s 2ms/step - loss: 764.7523
Epoch 8/1000
2/2 [==============================] - 0s 3ms/step - loss: 687.7032
Epoch 9/1000
2/2 [==============================] - 0s 3ms/step - loss: 342.2186
Epoch 10/1000
2/2 [==============================] - 0s 3ms/step - loss: 187.8512
Epoch 11/1000
2/2 [==============================] - 0s 3ms/step - loss: 258.6794
Epoch 12/1000
2/2 [==============================] - 0s 2ms/step - loss: 421.9357
Epoch 13/1000
2/2 [===============

In [88]:
y_pred=(model.predict(X_test))

1/1 [==============================] - 0s 115ms/step


In [89]:
y_pred

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.00

In [90]:
y_pred_val = np.where(y_pred >= 0.5)

In [91]:
len(y_pred_val[1])

12

In [92]:
y_pred_val[1]

array([6, 3, 3, 4, 3, 3, 4, 3, 7, 8, 3, 3], dtype=int64)

In [93]:
y_test

43    4
11    3
22    3
3     4
33    3
1     4
26    4
27    4
12    7
13    8
45    3
32    3
Name: Snooze, dtype: int64

In [94]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_val[1])

0.75

In [95]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred_val[1]))

[[5 0 0 0 0]
 [2 2 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [96]:
import joblib

joblib.dump(model, 'model_v2.pkl')

# 2. Convert the exported model to TensorFlow Lite format
v1_model = joblib.load('model_v2.pkl')

# Convert the logistic regression model to TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(v1_model)
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\navan\AppData\Local\Temp\tmptf8idocr\assets


INFO:tensorflow:Assets written to: C:\Users\navan\AppData\Local\Temp\tmptf8idocr\assets


In [ ]:
# # Save the TFLite model to a file
with open('model_v2_model.tflite', 'wb') as f:
    f.write(tflite_model)